/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CodeSend: typeof import('./../src/components/CodeSend/index.vue')['default']
    ComponentsAppMain: typeof import('./../src/layout/components/AppMain.vue')['default']
    ComponentsBreadcrumb: typeof import('./../src/layout/components/Breadcrumb/index.vue')['default']
    ComponentsHamburger: typeof import('./../src/layout/components/Hamburger/index.vue')['default']
    ComponentsNavigationBar: typeof import('./../src/layout/components/NavigationBar/index.vue')['default']
    ComponentsRightPanel: typeof import('./../src/layout/components/RightPanel/index.vue')['default']
    ComponentsSettings: typeof import('./../src/layout/components/Settings/index.vue')['default']
    ComponentsSidebar: typeof import('./../src/layout/components/Sidebar/index.vue')['default']
    ComponentsSidebarSidebarItem: typeof import('./../src/layout/components/Sidebar/SidebarItem.vue')['default']
    ComponentsSidebarSidebarItemLink: typeof import('./../src/layout/components/Sidebar/SidebarItemLink.vue')['default']
    ComponentsSidebarSidebarLogo: typeof import('./../src/layout/components/Sidebar/SidebarLogo.vue')['default']
    ComponentsTagsView: typeof import('./../src/layout/components/TagsView/index.vue')['default']
    ComponentsTagsViewScrollPane: typeof import('./../src/layout/components/TagsView/ScrollPane.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Form: typeof import('./../src/components/Form/index.vue')['default']
    ImageCode: typeof import('./../src/components/ImageCode/index.vue')['default']
    Notify: typeof import('./../src/components/Notify/index.vue')['default']
    NotifyNotifyList: typeof import('./../src/components/Notify/NotifyList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./../src/components/Screenfull/index.vue')['default']
    Search: typeof import('./../src/components/Search/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    Table: typeof import('./../src/components/Table/index.vue')['default']
    ThemeSwitch: typeof import('./../src/components/ThemeSwitch/index.vue')['default']
    Update: typeof import('./../src/components/Update/index.vue')['default']
    WangEditor: typeof import('./../src/components/WangEditor/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
